#
# Metrics services -- provides a web GUI to monitor Lighthouse nodes.
#
version: "3.3"

services:
    prometheus:
        build:
            context: prometheus
        volumes:
            - prometheus-data:/prometheus
            - type: bind
              source: ./scrape-targets
              target: /prometheus/targets
        restart: always
        # network_mode: host
        extra_hosts:
          - "host.docker.internal:host-gateway"
          - "localhost:host-gateway"
        ports:
          - "0.0.0.0:9090:9090"
    grafana:
        build:
            context: grafana
        volumes:
            - grafana-data:/var/lib/grafana
        restart: always
        # network_mode: host
        extra_hosts:
          - "host.docker.internal:host-gateway"
          - "localhost:host-gateway"
        ports:
          - "0.0.0.0:3000:3000"
        #   - "host.docker.internal:192.168.0.105"

volumes:
    grafana-data:
    prometheus-data:
    targets:
